version: "3"
services:
  web:
    image: 191758827001.dkr.ecr.us-west-2.amazonaws.com/devops-dashboard-eks
    network_mode: host
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./devops-dashboard.env
    entrypoint:
      - /bin/sh
      - -c
      - 'npm start'
