version: "3"
services:
  web:
    image: ramvignesh/devops-dashboard
    network_mode: host
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./devops-dashboard.env
    entrypoint:
      - /bin/sh
      - -c
      - 'npm start'
